{% set name = "r-retip" %}
{% set version = "0.5.4" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/PaoloBnn/Retip/archive/v{{ version }}.tar.gz
    sha256: 8aeb6e6326fc5fd56c3757549c6571aa271fc41d28a1f9a4db3fe30fc23f290c

build:
    noarch: generic
    script: R CMD INSTALL .

requirements:
    host:
        - r-rcdklibs
        - r-rjava
        - r-png
        - r-ggplot2
        - r-modelmetrics
        - r-keras
        - r-caret
        - r-xgboost
        - r-doparallel
        - r-brnn
        - r-rcdk
        - r-dplyr
        - r-randomforest
        - r-readxl
    run:
        - r-rcdklibs
        - r-rjava
        - r-png
        - r-ggplot2
        - r-modelmetrics
        - r-keras
        - r-caret
        - r-xgboost
        - r-doparallel
        - r-brnn
        - r-rcdk
        - r-dplyr
        - r-randomforest
        - r-readxl

test:
    commands:
        - $R -e "library('retip')"           # [not win]
        - "\"%R%\" -e \"library('retip')\""  # [win]

about:
    home: https://github.com/PaoloBnn/Retip
    license: CC BY 4.0
    summary: Retention time prediction for metabolomics
    description: |
        Predicted retention time can be useful in liquid chromatography 
        analysis to identify unknowns and removing false positive annotations. 
        It uses five different machine learning algorithms to built a stable,
        accurate and fast RT prediction model. Retip also includes 20 useful 
        biochemical databases.
