{% set version = "0.5.4" %}

# whats the difference between traditional Galaxy packages and Conda packages?

package:
        name: r-retip
        version: {{ version }}

source:
        git_url: https://github.com/PaoloBnn/Retip.git
        git_rev: v{{ version }}

build:
        noarch: generic # is it fine to have R packages declared as generic?
        script: R CMD INSTALL .
        # number: what are the use cases of build number? is it possible do conda install of a package with a specific build number
        # rpaths: what are they doing? is it relevant for R-only packages? Is this transive?

requirements:
        build:
                - r-rcdklibs
                - r-rjava
                - r-png
                - r-ggplot2
                - r-modelmetrics
                - r-keras
                - r-caret
                - r-xgboost
                - r-doparallel
                - r-brnn
                - r-rcdk
                - r-dplyr
                - r-randomforest
                - r-readxl
        run:    # do we need to copy the run list from the build list? what is host list exactly?
                - r-rcdklibs
                - r-rjava
                - r-png
                - r-ggplot2
                - r-modelmetrics
                - r-keras
                - r-caret
                - r-xgboost
                - r-doparallel
                - r-brnn
                - r-rcdk
                - r-dplyr
                - r-randomforest
                - r-readxl
        # entry_points: what are those?

about:
        home: https://github.com/PaoloBnn/Retip