# .shed.yml supporting automatic pushes.
owner: recetox
categories:
  - TEST
repositories:
  retip:
    description: "Retention Time Prediction for Metabolomics."
    include:
      - retip.xml
toolshed:
  - localhost:9009